//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAURANTE.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RESTAURANTE.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregado.
        /// </summary>
        internal static string agregado {
            get {
                return ResourceManager.GetString("agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btn_editar {
            get {
                return ResourceManager.GetString("btn_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string btn_ingresar {
            get {
                return ResourceManager.GetString("btn_ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra la camara.
        /// </summary>
        internal static string camara_mensaje {
            get {
                return ResourceManager.GetString("camara_mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string cantidad {
            get {
                return ResourceManager.GetString("cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria.
        /// </summary>
        internal static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Click para agregar al carrito!.
        /// </summary>
        internal static string click {
            get {
                return ResourceManager.GetString("click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea confirmar el pedido?.
        /// </summary>
        internal static string confirmar_pedido_pregunta {
            get {
                return ResourceManager.GetString("confirmar_pedido_pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string contraseña {
            get {
                return ResourceManager.GetString("contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese una contraseña valida.
        /// </summary>
        internal static string contraseña_invalida {
            get {
                return ResourceManager.GetString("contraseña_invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectivo.
        /// </summary>
        internal static string efectivo {
            get {
                return ResourceManager.GetString("efectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion.
        /// </summary>
        internal static string informacion {
            get {
                return ResourceManager.GetString("informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llamar mesero.
        /// </summary>
        internal static string llamar_mesero_menu {
            get {
                return ResourceManager.GetString("llamar_mesero_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego.
        /// </summary>
        internal static string mensaje_agregado {
            get {
                return ResourceManager.GetString("mensaje_agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavia no tienes productos en el carrito.
        /// </summary>
        internal static string mensaje_carrito {
            get {
                return ResourceManager.GetString("mensaje_carrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        internal static string menu_menu {
            get {
                return ResourceManager.GetString("menu_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mesero asignado.
        /// </summary>
        internal static string mesero_asignado {
            get {
                return ResourceManager.GetString("mesero_asignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mesero vendra en unos minutos y traera el datafono.
        /// </summary>
        internal static string mesero_datafono {
            get {
                return ResourceManager.GetString("mesero_datafono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mesero vendra en unos minutos.
        /// </summary>
        internal static string mesero_viene {
            get {
                return ResourceManager.GetString("mesero_viene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi carrito.
        /// </summary>
        internal static string mi_carrito_menu {
            get {
                return ResourceManager.GetString("mi_carrito_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavia no has escogido ningun producto.
        /// </summary>
        internal static string no_escogido_productos {
            get {
                return ResourceManager.GetString("no_escogido_productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de mesa.
        /// </summary>
        internal static string numero_mesa {
            get {
                return ResourceManager.GetString("numero_mesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        internal static string pagar_menu {
            get {
                return ResourceManager.GetString("pagar_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pedido ya fue confirmado.
        /// </summary>
        internal static string pedido_confirmado {
            get {
                return ResourceManager.GetString("pedido_confirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pedido ya fue confirmado asi que no se puede eliminar.
        /// </summary>
        internal static string pedido_confirmado1 {
            get {
                return ResourceManager.GetString("pedido_confirmado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pedido ya fue confirmado asi que no se puede editar.
        /// </summary>
        internal static string pedido_confirmado2 {
            get {
                return ResourceManager.GetString("pedido_confirmado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pedido ha sido enviado a la cocina.
        /// </summary>
        internal static string pedido_enviado {
            get {
                return ResourceManager.GetString("pedido_enviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavia no se ha confirmado el pedido.
        /// </summary>
        internal static string pedido_vacio {
            get {
                return ResourceManager.GetString("pedido_vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string precio {
            get {
                return ResourceManager.GetString("precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas con la conexion.
        /// </summary>
        internal static string problemas_conexion {
            get {
                return ResourceManager.GetString("problemas_conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string producto {
            get {
                return ResourceManager.GetString("producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El producto ya esta agregado en el carrito de compras.
        /// </summary>
        internal static string producto_escogido {
            get {
                return ResourceManager.GetString("producto_escogido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publicaciones.
        /// </summary>
        internal static string publicaciones {
            get {
                return ResourceManager.GetString("publicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publicar.
        /// </summary>
        internal static string publicar_btn {
            get {
                return ResourceManager.GetString("publicar_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta.
        /// </summary>
        internal static string tarjeta {
            get {
                return ResourceManager.GetString("tarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un usuario valido.
        /// </summary>
        internal static string usuario_invalido {
            get {
                return ResourceManager.GetString("usuario_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe, vuelva a intentarlo..
        /// </summary>
        internal static string vuelva_intentar {
            get {
                return ResourceManager.GetString("vuelva_intentar", resourceCulture);
            }
        }
    }
}
